---
- name: Create SSH Key Folder
  ansible.builtin.file:
    path: ~/.ssh
    state: directory
    mode: 0700

- name: Install SSH Private Key
  ansible.builtin.copy:
    content: "{{ SSH_PRIVATE_KEY }}"
    dest: ~/.ssh/id_ed25519
    mode: 0600

- name: Install SSH Public Key
  ansible.builtin.copy:
    content: "{{ SSH_PUBLIC_KEY }}"
    dest: ~/.ssh/id_ed25519.pub
    mode: 0600

- name: Add Authorized Keys
  ansible.posix.authorized_key:
    key: "{{ item }}"
    user: root
  loop: "{{ SSH_AUTHORIZED_KEYS | default([]) }}"
