---
- name: Install aptitude
  ansible.builtin.apt:
    name: aptitude
    state: present

- name: Install required system packages
  ansible.builtin.apt:
    pkg:
      - gnupg
    state: present

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/debian bookworm stable
    state: present

- name: Create Docker Directory
  ansible.builtin.file:
    path: /var/lib/docker
    state: directory
    mode: 0710

- name: Create Docker Data Directory
  ansible.builtin.file:
    path: "{{ data_directory }}/docker"
    state: directory
    mode: 0710

- name: Create Docker Data Volume Directory
  ansible.builtin.file:
    path: "{{ data_directory }}/docker/volumes"
    state: directory
    mode: '0701'

- name: Create Symlink to Store Volumes Separatly
  ansible.builtin.file:
    path: /var/lib/docker/volumes
    src: "{{ data_directory }}/docker/volumes"
    state: link
    mode: '0701'
    force: yes

- name: Update apt and install docker-ce
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true
