---
version: "3.7"

services:
  caddy:
    image: caddy:2.6.1-alpine
    restart: unless-stopped
    read_only: true
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - rproxy

volumes:
  caddy_data:
  caddy_config:

networks:
  rproxy:
    name: rproxy
