---
version: '2.4'

services:
  frontend:
    image: grocy/frontend:v3.3.2-4
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    networks:
      - default
      - rproxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.grocy.rule=Host(`grocy.$BASE_DOMAIN`)
      - traefik.http.routers.grocy.entrypoints=https
      - traefik.http.routers.grocy.tls.certResolver=letsencrypt
      - traefik.http.routers.grocy.middlewares=authelia@docker

  backend:
    image: grocy/backend:v3.3.2-4
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - app_db:/var/www/data
    env_file:
      - grocy.env
    networks:
      - default

volumes:
  app_db:

networks:
  default:
  rproxy:
    external: true
