---
version: '2.4'

services:
  frontend:
    image: grocy/frontend:v3.3.1
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/empty/docker:/var/log/nginx:ro
    networks:
      - default
      - rproxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.grocy.rule=Host(`grocy.pascal.build`)
      - traefik.http.routers.grocy.entrypoints=https
      - traefik.http.routers.grocy.tls.certResolver=letsencrypt

  backend:
    image: grocy/backend:v3.3.1
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - app_db:/var/www/data
      - ./php-fpm.conf:/etc/php8/php-fpm.d/z-php-fpm.conf:ro
    env_file:
      - grocy.env
    networks:
      - default

volumes:
  app_db:

networks:
  default:
  rproxy:
    external: true
