---
version: '3'

services:
  lldap:
    image: nitnelave/lldap:latest-alpine
    entrypoint: /app/lldap
    command: ["run", "--config-file", "/data/lldap_config.toml"]
    restart: unless-stopped
    read_only: true
    environment:
      LLDAP_JWT_SECRET: ${JWT_SECRET}
      LLDAP_LDAP_USER_PASS: ${USER_PASSWORD}
      LLDAP_LDAP_BASE_DN: dc=pascal,dc=build
      # LLDAP_VERBOSE: "true"
    volumes:
      - lldap_data:/data/dynamic
      - ./lldap_config.toml:/data/lldap_config.toml:ro
    networks:
      - ldap
      - rproxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.lldap.rule=Host(`ldap.localhost`)
      - traefik.http.routers.lldap.entrypoints=https
      - traefik.http.routers.lldap.tls.certResolver=letsencrypt
      - traefik.http.services.lldap.loadbalancer.server.port=17170

volumes:
  lldap_data:

networks:
  rproxy:
    external: true
  ldap:
    name: ldap
