---
- name: Set Secrets
  ansible.builtin.set_fact:
    "{{ item }}": >-
      {{
        vars[item]
        | default(lookup('ansible.builtin.env', item))
      }}
  delegate_to: localhost
  loop:
    - AUTHELIA_JWT_SECRET
    - AUTHELIA_SESSION_SECRET
    - AUTHELIA_POSTGRES_PASSWORD
    - AUTHELIA_STORAGE_ENCRYPTION_KEY
    - AUTHELIA_LDAP_PASSWORD
    - AUTHELIA_NOTIFIER_SMTP_PASSWORD
    - LLDAP_ADMIN_PASSWORD
    - LLDAP_JWT_SECRET
    - BORG_BACKUP_ENCRYPTION_PASS
    - BORG_BACKUP_REPOSITORY
    - SSH_PRIVATE_KEY
    - SSH_PUBLIC_KEY
