---
- name: Copy Docker Daemon Config
  ansible.builtin.copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: 0644
  notify:
    - Restart Docker Daemon

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
