---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: debian:10
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
    ANSIBLE_PIPELINING: "True"
verifier:
  name: ansible
lint: |
  yamllint .
  ansible-lint .
