---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: qemu
platforms:
  - name: instance
    box: debian/bullseye64
    provider_options:
      qemu_dir: /usr/bin/
      arch: x86_64
      machine: q35
      cpu: max
      net_device: virtio-net-pci
    provider_raw_config_args:
      - extra_qemu_args = %w(-vga std $QEMU_ARGS)
provisioner:
  name: ansible
  playbooks:
    side_effect: install_old_app.yml
  env:
    ANSIBLE_PIPELINING: "True"
  inventory:
    host_vars:
      instance:
        letsencrypt: no
verifier:
  name: ansible
lint: ansible-lint
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
