---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Get docker-compose Services
      ansible.builtin.stat:
        path: /srv/caddy
      register: stat_result

    - name: Verify docker-compose Services
      ansible.builtin.assert:
        that: stat_result.stat.exists

    - name: Get Docker Version
      ansible.builtin.command: docker -v
      register: docker_version

    - name: Verify Docker Version
      ansible.builtin.assert:
        that: '"version 20" in docker_version.stdout'

    - name: Verify Reverse Proxy Response
      ansible.builtin.uri:
        url: https://localhost/
        validate_certs: no

    - name: Verify Grocy Reverse Proxy Response
      ansible.builtin.uri:
        url: https://localhost/login
        validate_certs: no
        headers:
          Host: grocy.pascal.build
