---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Get Docker Version
    ansible.builtin.command: docker -v
    register: docker_version
  
  - name: Verify Docker Version
    ansible.builtin.assert:
      that: '"version 20" in docker_version.stdout'
