---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Get Docker Version
      community.docker.docker_host_info:
        volumes: yes
      register: docker_host_info
      become: true

    - name: Get List of Anonymous volumes
      ansible.builtin.set_fact:
        docker_anonymous_volumes: >-
          {{
          docker_host_info
          | community.general.json_query('volumes[*].Name')
          | select('match', '^[0-9a-f]{64}$')
          }}

    - name: Verify that no Anonymous Volumes exist
      ansible.builtin.assert:
        that: not docker_anonymous_volumes
        fail_msg: >-
          Expected no anonymous volumes, found:
          {{ docker_anonymous_volumes }}

    - name: Get Docker Volume
      ansible.builtin.stat:
        path: /mnt/data/docker/volumes/caddy_caddy_data
      register: docker_volume
      become: true

    - name: Verify Docker Volume Location
      ansible.builtin.assert:
        that: docker_volume.stat.exists

    - name: Get docker-compose Services
      ansible.builtin.stat:
        path: /srv/caddy
      register: stat_result

    - name: Verify docker-compose Services
      ansible.builtin.assert:
        that: stat_result.stat.exists

    - name: Verify Reverse Proxy Response
      ansible.builtin.uri:
        url: https://localhost/
        validate_certs: no

    - name: Verify Grocy Reverse Proxy Response
      ansible.builtin.uri:
        url: https://localhost/login
        validate_certs: no
        headers:
          Host: grocy.pascal.build
