---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Get Docker Version
      community.docker.docker_host_info:
        volumes: yes
      register: docker_host_info
      become: true

    - name: Get List of Anonymous volumes
      ansible.builtin.set_fact:
        docker_anonymous_volumes: >-
          {{
          docker_host_info.volumes
          | map(attribute='Name')
          | select('match', '^[0-9a-f]{64}$')
          }}

    - name: Verify that no Anonymous Volumes exist
      ansible.builtin.assert:
        that: not docker_anonymous_volumes
        fail_msg: >-
          Expected no anonymous volumes, found:
          {{ docker_anonymous_volumes }}

    - name: Get Docker Volume
      ansible.builtin.stat:
        path: /mnt/data/docker/volumes/traefik_letsencrypt
      register: docker_volume
      become: true

    - name: Verify Docker Volume Location
      ansible.builtin.assert:
        that: docker_volume.stat.exists

    - name: Get docker-compose Services
      ansible.builtin.stat:
        path: /srv/traefik
      register: stat_result

    - name: Verify docker-compose Services
      ansible.builtin.assert:
        that: stat_result.stat.exists

    - name: Get Grocy Reverse Proxy Response
      ansible.builtin.uri:
        url: https://localhost/login
        return_content: yes
        validate_certs: no
        headers:
          Host: grocy.pascal.build
      register: grocy_response

    - name: Verify Grocy Reverse Proxy Response
      ansible.builtin.assert:
        that: >-
          'content="grocy"' in grocy_response.content

    - name: Get Test Docker Compose Application
      ansible.builtin.stat:
        path: /srv/test_app
      register: test_compose_app

    - name: Test Docker Compose Application
      ansible.builtin.assert:
        that: not test_compose_app.stat.exists
