---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Get Docker Version
      ansible.builtin.command: docker -v
      register: docker_version

    - name: Verify Docker Version
      ansible.builtin.assert:
        that: '"version 20" in docker_version.stdout'

    - name: Get Docker Volume
      ansible.builtin.stat:
        path: /mnt/data/docker/volumes/caddy_caddy_data
      register: docker_volume
      become: true

    - name: Verify Docker Volume Location
      ansible.builtin.assert:
        that: docker_volume.stat.exists

    - name: Get List of Anonymous Volumes
      ansible.builtin.command:
        cmd: "{% raw %}docker volume list --format '{{.Name}}'{% endraw %}"
      changed_when: false
      register: docker_anonymous_volumes
      become: true

    - name: Verify that no Anonymous Volumes exist
      ansible.builtin.assert:
        that: |-
          not (
            docker_anonymous_volumes.stdout
            | regex_findall('^[0-9a-f]{64}$', multiline=True, ignorecase=True)
          )

    - name: Get docker-compose Services
      ansible.builtin.stat:
        path: /srv/caddy
      register: stat_result

    - name: Verify docker-compose Services
      ansible.builtin.assert:
        that: stat_result.stat.exists

    - name: Verify Reverse Proxy Response
      ansible.builtin.uri:
        url: https://localhost/
        validate_certs: no

    - name: Verify Grocy Reverse Proxy Response
      ansible.builtin.uri:
        url: https://localhost/login
        validate_certs: no
        headers:
          Host: grocy.pascal.build
