---
- name: Copy docker-compose applications to target
  ansible.builtin.copy:
    src: "."
    dest: "/srv/"

- name: Get All docker compose Services
  ansible.builtin.find:
    paths: /srv
    patterns: docker-compose.yml
    recurse: yes
    depth: 2
  register: find

- name: Start docker-compose services
  ansible.builtin.command:
    cmd: docker compose up --detach --remove-orphans
    chdir: "/srv/{{ service }}"
  vars:
    service: "{{ item.path | dirname | basename }}"
  changed_when: "'done' in compose.stdout"
  register: compose
  loop: "{{ find.files }}"
