---
- name: Get Installed Applications
  ansible.builtin.find:
    paths: /srv
    patterns: docker-compose.yml
    recurse: yes
    depth: 2
  register: docker_compose_files

- name: Get Applications to Remove
  ansible.builtin.set_fact:
    apps_to_uninstall: >-
      {{
        docker_compose_files.files
        | map(attribute='path')
        | map('dirname')
        | map('basename')
        | difference(apps)
      }}

- name: Set Secrets
  ansible.builtin.set_fact:
    "{{ item }}": "{{ lookup('ansible.builtin.env', item) }}"
  delegate_to: localhost
  loop:
    - AUTHELIA_JWT_SECRET
    - AUTHELIA_SESSION_SECRET
    - AUTHELIA_POSTGRES_PASSWORD
    - AUTHELIA_STORAGE_ENCRYPTION_KEY
    - AUTHELIA_LDAP_PASSWORD
    - LLDAP_ADMIN_PASSWORD
    - LLDAP_JWT_SECRET

- name: Uninstall Docker Compose Applications
  ansible.builtin.include_role:
    name: docker_compose_app
  vars:
    state: absent
  loop: "{{ apps_to_uninstall }}"
  loop_control:
    loop_var: app

- name: Install Docker Compose Applications
  ansible.builtin.include_role:
    name: docker_compose_app
  loop: "{{ apps }}"
  loop_control:
    loop_var: app
