---
- name: Copy docker-compose applications to target
  ansible.builtin.copy:
    src: "."
    dest: "/srv/"

- name: Get All docker compose Services
  ansible.builtin.find:
    paths: /srv
    patterns: docker-compose.yml
    recurse: yes
    depth: 2
  register: find

- name: Start docker-compose services
  community.docker.docker_compose:
    project_src: "/srv/{{ service }}"
    remove_orphans: yes
  vars:
    service: "{{ item.path | dirname | basename }}"
  register: compose
  loop: "{{ find.files }}"
