---
version: "3.7"

services:
  traefik:
    image: traefik:v2.9
    restart: unless-stopped
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
      - 0.0.0.0:443:443/udp
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
    networks:
      - rproxy

volumes:
  letsencrypt:

networks:
  rproxy:
    name: rproxy
