---
version: "3.7"

services:
  traefik:
    image: traefik:v3.0.0-beta2
    restart: unless-stopped
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
      - 0.0.0.0:443:443/udp
      - "[::]:80:80"
      - "[::]:443:443"
      - "[::]:443:443/udp"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.rule=Host(`traefik.$BASE_DOMAIN`)
      - traefik.http.routers.traefik.entrypoints=https
      - traefik.http.routers.traefik.tls.certResolver=letsencrypt
      - traefik.http.routers.traefik.middlewares=authelia@docker
    networks:
      - rproxy
      - observability

volumes:
  letsencrypt:

networks:
  rproxy:
    name: rproxy
  observability:
    external: true
