---
version: '2.4'

services:
  grocy:
    image: "grocy/frontend:v3.3.1"
    read_only: true
    tmpfs:
      - /tmp
    networks:
      - default
      - rproxy

  backend:
    image: "grocy/backend:v3.3.1"
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - app-db:/var/www/data
      - ./php-fpm.conf:/etc/php8/php-fpm.d/z-php-fpm.conf
    env_file:
      - grocy.env
    networks:
      - default

volumes:
  app-db:

networks:
  default:
  rproxy:
    external: true
