name: Ansible

on: push

permissions:
  contents: read

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: software
    steps:
      - uses: actions/checkout@v2
      - uses: gofrolist/molecule-action@v2