name: Ansible

on:
  pull_request:

permissions:
  contents: read

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: redlinetriad/molecule-vagrant-qemu-action@v1
        with:
          molecule_working_dir: software
        