name: Ansible

on: push

permissions:
  contents: read

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: Test Molecule default pipeline
        env:
          ANSIBLE_FORCE_COLOR: '1'
        run: |
          docker run \
          -v $(pwd)/:/repo \
          ghcr.io/redlinetriad/molecule-vagrant-qemu-action:v1 \
          sh -c "\
            molecule --version \
            && cd /repo \
            && molecule test \
          "
        