name: Ansible

on:
  pull_request:

permissions:
  contents: read

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - uses: redlinetriad/molecule-vagrant-qemu-action@v1
        with:
          molecule_working_dir: software
        